### PR TITLE
Meta cell add crossreg notebook to the RTD documentation

### PR DESCRIPTION
**Pull request by zsinnema**

### CODE REVIEW

**Comment by phildong** [comment]
hmm why does this PR has 4000+ file changes as well? anyway I can just review the documentation changes?

**Comment by zsinnema** [comment]
yes

**Comment by phildong** [comment]
just making sure by "yes" you mean "yes it's possible to get rid of 4000+ changes so that I can review the docs, and I will wait for you to finish that before proceeding to review"?

**Comment by zsinnema** [comment]
Yes I can do that for you. No problem. I'll do it tomorrow morning

**Pull request closed without merging**
